import type { SiteData } from '@azimut/core-model';

export const refMinimal: SiteData = {
  organization: {
    id: 'org-test-001',
    name: 'Test Organisation',
    slug: 'test-org',
  },
  site: {
    id: 'site-minimal-001',
    org_id: 'org-test-001',
    name: 'Site minimal',
    country_code: 'FR',
    rules_pack_id: null,
  },
  buildings: [
    {
      id: 'bldg-001',
      org_id: 'org-test-001',
      site_id: 'site-minimal-001',
      name: 'Bâtiment principal',
      independent_access: true,
    },
  ],
  levels: [
    {
      id: 'lvl-001',
      org_id: 'org-test-001',
      building_id: 'bldg-001',
      name: 'Rez-de-chaussée',
      ordinal: 0,
      elevation_m: 0,
    },
  ],
  footprints: [
    {
      id: 'fp-001',
      org_id: 'org-test-001',
      level_id: 'lvl-001',
      geometry: {
        vertices: [
          { x_m: 0, y_m: 0 },
          { x_m: 30, y_m: 0 },
          { x_m: 30, y_m: 20 },
          { x_m: 0, y_m: 20 },
        ],
      },
      kind: 'room',
    },
  ],
  volumes: [
    {
      id: 'vol-001',
      org_id: 'org-test-001',
      footprint_id: 'fp-001',
      base_elevation_m: 0,
      height_m: 3,
      material_key: 'concrete',
    },
  ],
  graph: {
    nodes: [
      {
        id: 'n-entrance',
        org_id: 'org-test-001',
        level_id: 'lvl-001',
        kind: 'entrance',
        position: { x_m: 15, y_m: 0 },
        label: 'Entrée',
      },
      {
        id: 'n-junction',
        org_id: 'org-test-001',
        level_id: 'lvl-001',
        kind: 'junction',
        position: { x_m: 15, y_m: 10 },
        label: 'Carrefour',
      },
      {
        id: 'n-dest-a',
        org_id: 'org-test-001',
        level_id: 'lvl-001',
        kind: 'destination_access',
        position: { x_m: 5, y_m: 15 },
        label: 'Accès A',
      },
      {
        id: 'n-dest-b',
        org_id: 'org-test-001',
        level_id: 'lvl-001',
        kind: 'destination_access',
        position: { x_m: 25, y_m: 15 },
        label: 'Accès B',
      },
      {
        id: 'n-dest-c',
        org_id: 'org-test-001',
        level_id: 'lvl-001',
        kind: 'destination_access',
        position: { x_m: 5, y_m: 5 },
        label: 'Accès C',
      },
      {
        id: 'n-dest-d',
        org_id: 'org-test-001',
        level_id: 'lvl-001',
        kind: 'destination_access',
        position: { x_m: 25, y_m: 5 },
        label: 'Accès D',
      },
    ],
    edges: [
      {
        id: 'e-01',
        org_id: 'org-test-001',
        from_node_id: 'n-entrance',
        to_node_id: 'n-junction',
        width_m: 2,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: true,
        length_m: 10,
      },
      {
        id: 'e-02',
        org_id: 'org-test-001',
        from_node_id: 'n-junction',
        to_node_id: 'n-dest-a',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 11.18,
      },
      {
        id: 'e-03',
        org_id: 'org-test-001',
        from_node_id: 'n-junction',
        to_node_id: 'n-dest-b',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 11.18,
      },
      {
        id: 'e-04',
        org_id: 'org-test-001',
        from_node_id: 'n-junction',
        to_node_id: 'n-dest-c',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 11.18,
      },
      {
        id: 'e-05',
        org_id: 'org-test-001',
        from_node_id: 'n-junction',
        to_node_id: 'n-dest-d',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 11.18,
      },
    ],
    vertical_links: [],
  },
  categories: [
    {
      id: 'cat-office',
      org_id: 'org-test-001',
      sector_key: 'tertiary',
      code: 'office',
      parent_id: null,
    },
    {
      id: 'cat-restroom',
      org_id: 'org-test-001',
      sector_key: 'common',
      code: 'restroom',
      parent_id: null,
    },
  ],
  pictograms: [
    {
      id: 'picto-office-wayfinding',
      org_id: 'org-test-001',
      category_id: 'cat-office',
      source: 'internal',
      standard_ref: 'WF-001',
      svg_path: 'M10 10h20v20H10z',
      registry: 'wayfinding',
    },
    {
      id: 'picto-fire-exit-safety',
      org_id: 'org-test-001',
      category_id: 'cat-restroom',
      source: 'internal',
      standard_ref: 'SF-001',
      svg_path: 'M5 5l10 10M15 5L5 15',
      registry: 'safety',
    },
  ],
  destinations: [
    {
      id: 'dest-a',
      org_id: 'org-test-001',
      footprint_id: 'fp-001',
      node_id: 'n-dest-a',
      category_id: 'cat-office',
      occupant_name: 'Bureau A',
      occupancy_status: 'occupied',
      display_priority: 1,
    },
    {
      id: 'dest-b',
      org_id: 'org-test-001',
      footprint_id: 'fp-001',
      node_id: 'n-dest-b',
      category_id: 'cat-office',
      occupant_name: 'Bureau B',
      occupancy_status: 'occupied',
      display_priority: 2,
    },
    {
      id: 'dest-c',
      org_id: 'org-test-001',
      footprint_id: 'fp-001',
      node_id: 'n-dest-c',
      category_id: 'cat-office',
      occupant_name: 'Bureau C',
      occupancy_status: 'vacant',
      display_priority: 3,
    },
    {
      id: 'dest-d',
      org_id: 'org-test-001',
      footprint_id: 'fp-001',
      node_id: 'n-dest-d',
      category_id: 'cat-office',
      occupant_name: 'Bureau D',
      occupancy_status: 'occupied',
      display_priority: 4,
    },
  ],
  destination_names: [
    { id: 'dn-a-fr', org_id: 'org-test-001', destination_id: 'dest-a', lang: 'fr', value: 'Bureau A' },
    { id: 'dn-a-en', org_id: 'org-test-001', destination_id: 'dest-a', lang: 'en', value: 'Office A' },
    { id: 'dn-b-fr', org_id: 'org-test-001', destination_id: 'dest-b', lang: 'fr', value: 'Bureau B' },
    { id: 'dn-b-en', org_id: 'org-test-001', destination_id: 'dest-b', lang: 'en', value: 'Office B' },
    { id: 'dn-c-fr', org_id: 'org-test-001', destination_id: 'dest-c', lang: 'fr', value: 'Bureau C' },
    { id: 'dn-c-en', org_id: 'org-test-001', destination_id: 'dest-c', lang: 'en', value: 'Office C' },
    { id: 'dn-d-fr', org_id: 'org-test-001', destination_id: 'dest-d', lang: 'fr', value: 'Bureau D' },
    { id: 'dn-d-en', org_id: 'org-test-001', destination_id: 'dest-d', lang: 'en', value: 'Office D' },
  ],
  travel_profiles: [
    {
      id: 'tp-standard',
      org_id: 'org-test-001',
      site_id: 'site-minimal-001',
      key: 'standard',
      name: 'Visiteur standard',
      excluded_edge_kinds: [],
      require_accessible: false,
      honor_hours: false,
    },
  ],
};
