import type { SiteData } from '@azimut/core-model';

/**
 * Le graphe du site de référence multiniveau.
 *
 * Sorti du fichier principal, qu'il occupait à lui seul pour plus de la moitié
 * et qui franchissait les quatre cents lignes (A2.4). La donnée ne change pas :
 * la constante est réinjectée telle quelle dans `refMultilevel`.
 */
export const REF_MULTILEVEL_GRAPH: SiteData['graph'] = {
  nodes: [
    {
      id: 'n-ml-entrance',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-rdc',
      kind: 'entrance',
      position: { x_m: 20, y_m: 0 },
      label: 'Entrée',
    },
    {
      id: 'n-ml-hall',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-rdc',
      kind: 'junction',
      position: { x_m: 20, y_m: 10 },
      label: 'Hall RDC',
    },
    {
      id: 'n-ml-elevator-rdc',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-rdc',
      kind: 'elevator',
      position: { x_m: 10, y_m: 10 },
      label: 'Ascenseur RDC',
    },
    {
      id: 'n-ml-stair-rdc',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-rdc',
      kind: 'stair',
      position: { x_m: 30, y_m: 10 },
      label: 'Escalier RDC',
    },
    {
      id: 'n-ml-dest-rdc',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-rdc',
      kind: 'destination_access',
      position: { x_m: 5, y_m: 15 },
      label: 'Bureau RDC',
    },
    {
      id: 'n-ml-elevator-r1',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-r1',
      kind: 'elevator',
      position: { x_m: 10, y_m: 10 },
      label: 'Ascenseur R+1',
    },
    {
      id: 'n-ml-stair-r1',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-r1',
      kind: 'stair',
      position: { x_m: 30, y_m: 10 },
      label: 'Escalier R+1',
    },
    {
      id: 'n-ml-hall-r1',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-r1',
      kind: 'junction',
      position: { x_m: 20, y_m: 10 },
      label: 'Hall R+1',
    },
    {
      id: 'n-ml-dest-r1',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-r1',
      kind: 'destination_access',
      position: { x_m: 35, y_m: 15 },
      label: 'Bureau R+1',
    },
  ],
  edges: [
    {
      id: 'e-ml-entrance-hall',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-entrance',
      to_node_id: 'n-ml-hall',
      width_m: 2,
      slope_pct: 0,
      accessible: true,
      direction: 'both',
      evacuation_route: true,
      length_m: 10,
    },
    {
      id: 'e-ml-hall-elevator',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-hall',
      to_node_id: 'n-ml-elevator-rdc',
      width_m: 1.5,
      slope_pct: 0,
      accessible: true,
      direction: 'both',
      evacuation_route: false,
      length_m: 10,
    },
    {
      id: 'e-ml-hall-stair',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-hall',
      to_node_id: 'n-ml-stair-rdc',
      width_m: 1.2,
      slope_pct: 0,
      accessible: false,
      direction: 'both',
      evacuation_route: true,
      length_m: 10,
    },
    {
      id: 'e-ml-hall-dest-rdc',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-hall',
      to_node_id: 'n-ml-dest-rdc',
      width_m: 1.5,
      slope_pct: 0,
      accessible: true,
      direction: 'both',
      evacuation_route: false,
      length_m: 15.81,
    },
    {
      id: 'e-ml-elevator-vl',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-elevator-rdc',
      to_node_id: 'n-ml-elevator-r1',
      width_m: 1.5,
      slope_pct: 0,
      accessible: true,
      direction: 'both',
      evacuation_route: false,
      length_m: 3,
    },
    {
      id: 'e-ml-stair-vl',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-stair-rdc',
      to_node_id: 'n-ml-stair-r1',
      width_m: 1.2,
      slope_pct: 0,
      accessible: false,
      direction: 'both',
      evacuation_route: true,
      length_m: 5,
    },
    {
      id: 'e-ml-elevator-r1-hall',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-elevator-r1',
      to_node_id: 'n-ml-hall-r1',
      width_m: 1.5,
      slope_pct: 0,
      accessible: true,
      direction: 'both',
      evacuation_route: false,
      length_m: 10,
    },
    {
      id: 'e-ml-stair-r1-hall',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-stair-r1',
      to_node_id: 'n-ml-hall-r1',
      width_m: 1.2,
      slope_pct: 0,
      accessible: false,
      direction: 'both',
      evacuation_route: true,
      length_m: 10,
    },
    {
      id: 'e-ml-hall-r1-dest',
      org_id: 'org-test-001',
      from_node_id: 'n-ml-hall-r1',
      to_node_id: 'n-ml-dest-r1',
      width_m: 1.5,
      slope_pct: 0,
      accessible: true,
      direction: 'both',
      evacuation_route: false,
      length_m: 15.81,
    },
  ],
  vertical_links: [
    {
      id: 'vl-ml-elevator',
      org_id: 'org-test-001',
      edge_id: 'e-ml-elevator-vl',
      kind: 'elevator',
      capacity: 8,
      accessible: true,
    },
    {
      id: 'vl-ml-stair',
      org_id: 'org-test-001',
      edge_id: 'e-ml-stair-vl',
      kind: 'stair',
      capacity: 50,
      accessible: false,
    },
  ],
};
