import type { SiteData } from '@azimut/core-model';

export const refBroken: SiteData = {
  organization: {
    id: 'org-test-001',
    name: 'Test Organisation',
    slug: 'test-org',
  },
  site: {
    id: 'site-broken-001',
    org_id: 'org-test-001',
    name: 'Site cassé',
    country_code: 'FR',
    rules_pack_id: null,
  },
  buildings: [
    {
      id: 'bldg-brk-001',
      org_id: 'org-test-001',
      site_id: 'site-broken-001',
      name: 'Bâtiment A',
      independent_access: true,
    },
  ],
  levels: [
    {
      id: 'lvl-brk-rdc',
      org_id: 'org-test-001',
      building_id: 'bldg-brk-001',
      name: 'RDC',
      ordinal: 0,
      elevation_m: 0,
    },
    {
      id: 'lvl-brk-r1',
      org_id: 'org-test-001',
      building_id: 'bldg-brk-001',
      name: 'R+1',
      ordinal: 1,
      elevation_m: 3,
    },
  ],
  footprints: [],
  volumes: [],
  graph: {
    nodes: [
      {
        id: 'n-brk-entrance',
        org_id: 'org-test-001',
        level_id: 'lvl-brk-rdc',
        kind: 'entrance',
        position: { x_m: 0, y_m: 0 },
        label: 'Entrée',
      },
      {
        id: 'n-brk-orphan',
        org_id: 'org-test-001',
        level_id: 'lvl-brk-rdc',
        kind: 'junction',
        position: { x_m: 50, y_m: 50 },
        label: 'Nœud orphelin',
      },
      {
        id: 'n-brk-deadend',
        org_id: 'org-test-001',
        level_id: 'lvl-brk-rdc',
        kind: 'junction',
        position: { x_m: 10, y_m: 0 },
        label: 'Impasse',
      },
      {
        id: 'n-brk-island-a',
        org_id: 'org-test-001',
        level_id: 'lvl-brk-rdc',
        kind: 'destination_access',
        position: { x_m: 80, y_m: 80 },
        label: 'Île A',
      },
      {
        id: 'n-brk-island-b',
        org_id: 'org-test-001',
        level_id: 'lvl-brk-rdc',
        kind: 'destination_access',
        position: { x_m: 90, y_m: 80 },
        label: 'Île B',
      },
      {
        id: 'n-brk-r1-landing',
        org_id: 'org-test-001',
        level_id: 'lvl-brk-r1',
        kind: 'landing',
        position: { x_m: 0, y_m: 0 },
        label: 'Palier R+1',
      },
    ],
    edges: [
      {
        id: 'e-brk-01',
        org_id: 'org-test-001',
        from_node_id: 'n-brk-entrance',
        to_node_id: 'n-brk-deadend',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 10,
      },
      {
        id: 'e-brk-zero-length',
        org_id: 'org-test-001',
        from_node_id: 'n-brk-entrance',
        to_node_id: 'n-brk-entrance',
        width_m: 1,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 0,
      },
      {
        id: 'e-brk-island',
        org_id: 'org-test-001',
        from_node_id: 'n-brk-island-a',
        to_node_id: 'n-brk-island-b',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 10,
      },
      {
        id: 'e-brk-cross-level',
        org_id: 'org-test-001',
        from_node_id: 'n-brk-entrance',
        to_node_id: 'n-brk-r1-landing',
        width_m: 1.2,
        slope_pct: 0,
        accessible: false,
        direction: 'both',
        evacuation_route: false,
        length_m: 5,
      },
    ],
    vertical_links: [],
  },
  destinations: [
    {
      id: 'dest-brk-unreachable',
      org_id: 'org-test-001',
      footprint_id: '',
      node_id: 'n-brk-island-a',
      category_id: 'cat-office',
      occupant_name: 'Bureau inatteignable',
      occupancy_status: 'occupied',
      display_priority: 1,
    },
  ],
  destination_names: [
    { id: 'dn-brk-fr', org_id: 'org-test-001', destination_id: 'dest-brk-unreachable', lang: 'fr', value: 'Bureau inatteignable' },
    { id: 'dn-brk-en', org_id: 'org-test-001', destination_id: 'dest-brk-unreachable', lang: 'en', value: 'Unreachable office' },
  ],
  travel_profiles: [
    {
      id: 'tp-brk-standard',
      org_id: 'org-test-001',
      site_id: 'site-broken-001',
      key: 'standard',
      name: 'Visiteur standard',
      excluded_edge_kinds: [],
      require_accessible: false,
      honor_hours: false,
    },
  ],
};
