import type { SiteData } from '@azimut/core-model';

export const refMultilevel: SiteData = {
  organization: {
    id: 'org-test-001',
    name: 'Test Organisation',
    slug: 'test-org',
  },
  site: {
    id: 'site-multilevel-001',
    org_id: 'org-test-001',
    name: 'Site multi-niveaux',
    country_code: 'FR',
    rules_pack_id: null,
  },
  buildings: [
    {
      id: 'bldg-ml-001',
      org_id: 'org-test-001',
      site_id: 'site-multilevel-001',
      name: 'Bâtiment ML',
      independent_access: true,
    },
  ],
  levels: [
    {
      id: 'lvl-ml-rdc',
      org_id: 'org-test-001',
      building_id: 'bldg-ml-001',
      name: 'RDC',
      ordinal: 0,
      elevation_m: 0,
    },
    {
      id: 'lvl-ml-r1',
      org_id: 'org-test-001',
      building_id: 'bldg-ml-001',
      name: 'R+1',
      ordinal: 1,
      elevation_m: 3,
    },
  ],
  footprints: [
    {
      id: 'fp-ml-rdc',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-rdc',
      geometry: {
        vertices: [
          { x_m: 0, y_m: 0 },
          { x_m: 40, y_m: 0 },
          { x_m: 40, y_m: 20 },
          { x_m: 0, y_m: 20 },
        ],
      },
      kind: 'room',
    },
    {
      id: 'fp-ml-r1',
      org_id: 'org-test-001',
      level_id: 'lvl-ml-r1',
      geometry: {
        vertices: [
          { x_m: 0, y_m: 0 },
          { x_m: 40, y_m: 0 },
          { x_m: 40, y_m: 20 },
          { x_m: 0, y_m: 20 },
        ],
      },
      kind: 'room',
    },
  ],
  volumes: [
    {
      id: 'vol-ml-rdc',
      org_id: 'org-test-001',
      footprint_id: 'fp-ml-rdc',
      base_elevation_m: 0,
      height_m: 3,
      material_key: 'concrete',
    },
    {
      id: 'vol-ml-r1',
      org_id: 'org-test-001',
      footprint_id: 'fp-ml-r1',
      base_elevation_m: 3,
      height_m: 3,
      material_key: 'concrete',
    },
  ],
  graph: {
    nodes: [
      {
        id: 'n-ml-entrance',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-rdc',
        kind: 'entrance',
        position: { x_m: 20, y_m: 0 },
        label: 'Entrée',
      },
      {
        id: 'n-ml-hall',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-rdc',
        kind: 'junction',
        position: { x_m: 20, y_m: 10 },
        label: 'Hall RDC',
      },
      {
        id: 'n-ml-elevator-rdc',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-rdc',
        kind: 'elevator',
        position: { x_m: 10, y_m: 10 },
        label: 'Ascenseur RDC',
      },
      {
        id: 'n-ml-stair-rdc',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-rdc',
        kind: 'stair',
        position: { x_m: 30, y_m: 10 },
        label: 'Escalier RDC',
      },
      {
        id: 'n-ml-dest-rdc',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-rdc',
        kind: 'destination_access',
        position: { x_m: 5, y_m: 15 },
        label: 'Bureau RDC',
      },
      {
        id: 'n-ml-elevator-r1',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-r1',
        kind: 'elevator',
        position: { x_m: 10, y_m: 10 },
        label: 'Ascenseur R+1',
      },
      {
        id: 'n-ml-stair-r1',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-r1',
        kind: 'stair',
        position: { x_m: 30, y_m: 10 },
        label: 'Escalier R+1',
      },
      {
        id: 'n-ml-hall-r1',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-r1',
        kind: 'junction',
        position: { x_m: 20, y_m: 10 },
        label: 'Hall R+1',
      },
      {
        id: 'n-ml-dest-r1',
        org_id: 'org-test-001',
        level_id: 'lvl-ml-r1',
        kind: 'destination_access',
        position: { x_m: 35, y_m: 15 },
        label: 'Bureau R+1',
      },
    ],
    edges: [
      {
        id: 'e-ml-entrance-hall',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-entrance',
        to_node_id: 'n-ml-hall',
        width_m: 2,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: true,
        length_m: 10,
      },
      {
        id: 'e-ml-hall-elevator',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-hall',
        to_node_id: 'n-ml-elevator-rdc',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 10,
      },
      {
        id: 'e-ml-hall-stair',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-hall',
        to_node_id: 'n-ml-stair-rdc',
        width_m: 1.2,
        slope_pct: 0,
        accessible: false,
        direction: 'both',
        evacuation_route: true,
        length_m: 10,
      },
      {
        id: 'e-ml-hall-dest-rdc',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-hall',
        to_node_id: 'n-ml-dest-rdc',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 15.81,
      },
      {
        id: 'e-ml-elevator-vl',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-elevator-rdc',
        to_node_id: 'n-ml-elevator-r1',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 3,
      },
      {
        id: 'e-ml-stair-vl',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-stair-rdc',
        to_node_id: 'n-ml-stair-r1',
        width_m: 1.2,
        slope_pct: 0,
        accessible: false,
        direction: 'both',
        evacuation_route: true,
        length_m: 5,
      },
      {
        id: 'e-ml-elevator-r1-hall',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-elevator-r1',
        to_node_id: 'n-ml-hall-r1',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 10,
      },
      {
        id: 'e-ml-stair-r1-hall',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-stair-r1',
        to_node_id: 'n-ml-hall-r1',
        width_m: 1.2,
        slope_pct: 0,
        accessible: false,
        direction: 'both',
        evacuation_route: true,
        length_m: 10,
      },
      {
        id: 'e-ml-hall-r1-dest',
        org_id: 'org-test-001',
        from_node_id: 'n-ml-hall-r1',
        to_node_id: 'n-ml-dest-r1',
        width_m: 1.5,
        slope_pct: 0,
        accessible: true,
        direction: 'both',
        evacuation_route: false,
        length_m: 15.81,
      },
    ],
    vertical_links: [
      {
        id: 'vl-ml-elevator',
        org_id: 'org-test-001',
        edge_id: 'e-ml-elevator-vl',
        kind: 'elevator',
        capacity: 8,
        accessible: true,
      },
      {
        id: 'vl-ml-stair',
        org_id: 'org-test-001',
        edge_id: 'e-ml-stair-vl',
        kind: 'stair',
        capacity: 50,
        accessible: false,
      },
    ],
  },
  destinations: [
    {
      id: 'dest-ml-rdc',
      org_id: 'org-test-001',
      footprint_id: 'fp-ml-rdc',
      node_id: 'n-ml-dest-rdc',
      category_id: 'cat-office',
      occupant_name: 'Bureau RDC',
      occupancy_status: 'occupied',
      display_priority: 1,
    },
    {
      id: 'dest-ml-r1',
      org_id: 'org-test-001',
      footprint_id: 'fp-ml-r1',
      node_id: 'n-ml-dest-r1',
      category_id: 'cat-office',
      occupant_name: 'Bureau R+1',
      occupancy_status: 'occupied',
      display_priority: 2,
    },
  ],
  destination_names: [
    { id: 'dn-ml-rdc-fr', org_id: 'org-test-001', destination_id: 'dest-ml-rdc', lang: 'fr', value: 'Bureau RDC' },
    { id: 'dn-ml-rdc-en', org_id: 'org-test-001', destination_id: 'dest-ml-rdc', lang: 'en', value: 'Ground floor office' },
    { id: 'dn-ml-r1-fr', org_id: 'org-test-001', destination_id: 'dest-ml-r1', lang: 'fr', value: 'Bureau R+1' },
    { id: 'dn-ml-r1-en', org_id: 'org-test-001', destination_id: 'dest-ml-r1', lang: 'en', value: 'First floor office' },
  ],
  travel_profiles: [
    {
      id: 'tp-ml-standard',
      org_id: 'org-test-001',
      site_id: 'site-multilevel-001',
      key: 'standard',
      name: 'Visiteur standard',
      excluded_edge_kinds: [],
      require_accessible: false,
      honor_hours: false,
    },
    {
      id: 'tp-ml-accessible',
      org_id: 'org-test-001',
      site_id: 'site-multilevel-001',
      key: 'accessible',
      name: 'Visiteur PMR',
      excluded_edge_kinds: [],
      require_accessible: true,
      honor_hours: false,
    },
    {
      id: 'tp-ml-evacuation',
      org_id: 'org-test-001',
      site_id: 'site-multilevel-001',
      key: 'evacuation',
      name: 'Évacuation',
      excluded_edge_kinds: ['elevator'],
      require_accessible: false,
      honor_hours: false,
    },
  ],
};
