/**
 * E5 + E7 — Command integration.
 *
 * Converts completed tool gestures into undoable commands.
 * When a tool's phase transitions to 'done', the preview geometry
 * is captured as a Command and pushed to the history stack.
 *
 * This module is the bridge between the tool state machine (ephemeral
 * drawing state) and the command history (persistent edit stack).
 *
 * The tool preview is quantized (E4) before becoming a command,
 * ensuring deterministic storage.
 */

import { quantizePoint } from '@azimut/core-model';
import type { Point } from '@azimut/core-model';
import type { Command } from './command.js';
import { createCommand } from './command.js';
import type { ToolPreview, ToolId } from './tool-state.js';

// ---------------------------------------------------------------------------
// Command types for each tool
// ---------------------------------------------------------------------------

export type RectCommandData = {
  readonly kind: 'rect';
  readonly origin: Point;
  readonly corner: Point;
};

export type EllipseCommandData = {
  readonly kind: 'ellipse';
  readonly center: Point;
  readonly rx_m: number;
  readonly ry_m: number;
};

export type PolygonCommandData = {
  readonly kind: 'polygon';
  readonly center: Point;
  readonly radius_m: number;
  readonly sides: number;
  readonly rotation_deg: number;
};

export type PolylineCommandData = {
  readonly kind: 'polyline';
  readonly points: readonly Point[];
};

export type MeasureCommandData = {
  readonly kind: 'measure';
  readonly from: Point;
  readonly to: Point;
};

export type DimensionCommandData = {
  readonly kind: 'dimension';
  readonly from: Point;
  readonly to: Point;
  readonly offset_m: number;
};

export type ShapeCommandData =
  | RectCommandData
  | EllipseCommandData
  | PolygonCommandData
  | PolylineCommandData
  | MeasureCommandData
  | DimensionCommandData;

// ---------------------------------------------------------------------------
// Preview → Command conversion
// ---------------------------------------------------------------------------

/**
 * Quantize a point to millimeter precision (E4.2).
 * Applied at command creation, not during the gesture.
 */
function qp(p: Point): Point {
  return quantizePoint(p);
}

/**
 * Map a tool id to the command type string.
 */
function commandType(toolId: ToolId): string {
  return `shape.create.${toolId}`;
}

/**
 * Convert a completed tool preview into a command.
 *
 * Returns null if the preview is empty or represents a zero-size shape.
 *
 * @param preview - The tool preview at phase 'done'.
 * @param toolId - The tool that produced the preview.
 * @param targetId - The id for the new object (generated by caller).
 * @param timestamp - ISO-8601 timestamp (provided by caller, E5).
 */
export function previewToCommand(
  preview: ToolPreview,
  toolId: ToolId,
  targetId: string,
  timestamp: string,
): Command<ShapeCommandData> | null {
  const data = previewToData(preview);
  if (data === null) return null;

  return createCommand<ShapeCommandData>(
    commandType(toolId),
    targetId,
    // 'before' is null-equivalent — this is a creation command.
    // We use the same shape with zero/empty values as 'before'
    // so the Command<T> type stays uniform.
    emptyData(data.kind),
    data,
    timestamp,
  );
}

/**
 * Extract quantized shape data from a tool preview.
 * Returns null for empty or degenerate shapes.
 */
function previewToData(preview: ToolPreview): ShapeCommandData | null {
  switch (preview.kind) {
    case 'none':
      return null;

    case 'rect': {
      const origin = qp(preview.origin);
      const corner = qp(preview.corner);
      // Reject zero-area rectangles
      if (origin.x_m === corner.x_m || origin.y_m === corner.y_m) {
        return null;
      }
      return { kind: 'rect', origin, corner };
    }

    case 'ellipse': {
      if (preview.rx_m <= 0 || preview.ry_m <= 0) return null;
      return {
        kind: 'ellipse',
        center: qp(preview.center),
        rx_m: preview.rx_m,
        ry_m: preview.ry_m,
      };
    }

    case 'polygon': {
      if (preview.radius_m <= 0 || preview.sides < 3) return null;
      return {
        kind: 'polygon',
        center: qp(preview.center),
        radius_m: preview.radius_m,
        sides: preview.sides,
        rotation_deg: preview.rotation_deg,
      };
    }

    case 'polyline':
    case 'bezier': {
      if (preview.points.length < 2) return null;
      return {
        kind: 'polyline',
        points: preview.points.map(qp),
      };
    }

    case 'measure': {
      const from = qp(preview.from);
      const to = qp(preview.to);
      if (from.x_m === to.x_m && from.y_m === to.y_m) return null;
      return { kind: 'measure', from, to };
    }

    case 'dimension': {
      const from = qp(preview.from);
      const to = qp(preview.to);
      if (from.x_m === to.x_m && from.y_m === to.y_m) return null;
      return { kind: 'dimension', from, to, offset_m: preview.offset_m };
    }
  }
}

/**
 * Create an "empty" data of the same kind, used as the 'before'
 * value in creation commands (so undo removes the shape entirely).
 */
function emptyData(kind: ShapeCommandData['kind']): ShapeCommandData {
  const zero: Point = { x_m: 0, y_m: 0 };
  switch (kind) {
    case 'rect':
      return { kind: 'rect', origin: zero, corner: zero };
    case 'ellipse':
      return { kind: 'ellipse', center: zero, rx_m: 0, ry_m: 0 };
    case 'polygon':
      return { kind: 'polygon', center: zero, radius_m: 0, sides: 3, rotation_deg: 0 };
    case 'polyline':
      return { kind: 'polyline', points: [] };
    case 'measure':
      return { kind: 'measure', from: zero, to: zero };
    case 'dimension':
      return { kind: 'dimension', from: zero, to: zero, offset_m: 0 };
  }
}
